// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVhmoZZSjUugXo0NC6raZFpcX9Npp4oz8',
    appId: '1:481270922121:web:c4010fd2017905617bbf58',
    messagingSenderId: '481270922121',
    projectId: 'flood-ops-b7dd9',
    authDomain: 'flood-ops-b7dd9.firebaseapp.com',
    storageBucket: 'flood-ops-b7dd9.firebasestorage.app',
    measurementId: 'G-59Z58EMNML',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqAQ9Yjpo7VFA5mE5SLqHyGeoIpkle8RM',
    appId: '1:481270922121:ios:10faa5a63aaa3c927bbf58',
    messagingSenderId: '481270922121',
    projectId: 'flood-ops-b7dd9',
    storageBucket: 'flood-ops-b7dd9.firebasestorage.app',
    iosBundleId: 'com.floodops.floodopsFrontend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqAQ9Yjpo7VFA5mE5SLqHyGeoIpkle8RM',
    appId: '1:481270922121:ios:10faa5a63aaa3c927bbf58',
    messagingSenderId: '481270922121',
    projectId: 'flood-ops-b7dd9',
    storageBucket: 'flood-ops-b7dd9.firebasestorage.app',
    iosBundleId: 'com.floodops.floodopsFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVhmoZZSjUugXo0NC6raZFpcX9Npp4oz8',
    appId: '1:481270922121:web:a48bbabef91002287bbf58',
    messagingSenderId: '481270922121',
    projectId: 'flood-ops-b7dd9',
    authDomain: 'flood-ops-b7dd9.firebaseapp.com',
    storageBucket: 'flood-ops-b7dd9.firebasestorage.app',
    measurementId: 'G-VS6LGK7TT7',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAltD8Vj_ynXvOsukfWbufyF1WB5IWIj88',
    appId: '1:481270922121:android:31740d051fa5849d7bbf58',
    messagingSenderId: '481270922121',
    projectId: 'flood-ops-b7dd9',
    storageBucket: 'flood-ops-b7dd9.firebasestorage.app',
  );
}
